import { FormModules, type FormTemplateDef } from "#/shared/types/dynamic-form";
import {
	academicLevels,
	graduationModalities,
	modalities,
	teachingAcademicLevels,
	teachingCategories,
	workloads,
} from "./seed-data";

export const studentFormTemplates: FormTemplateDef[] = [
	{
		id: "1",
		title: "Postulantes",
		description: "Número de postulantes por modalidad y sexo",
		module: FormModules.student,
		isActive: true,
		step: 1,
		hasBulk: true,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: modalities.map((modality) => ({
					value: modality.id,
					label: modality.modality,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "2",
		title: "Postulantes admitidos",
		description: "Número de postulantes admitidos por modalidad y sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: true,
		step: 2,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: modalities.map((modality) => ({
					value: modality.id,
					label: modality.modality,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "3",
		title: "Matrícula",
		description: "Matrícula estudiantil por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 3,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "4",
		title: "Matricula nuevos",
		description: "Matricula estudiantes nuevos por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 4,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "5",
		title: "Estudiantes programados",
		description: "Número de estudiantes programados por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 5,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "6",
		title: "Evaluacion Quantitativa",
		description:
			"Número de estudiantes aprobados, reprobados y abandonos de materias",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 6,
		fields: [
			{
				id: "1",
				name: "aprobados",
				label: "Aprobados",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "reprobados",
				label: "Reprobados",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "abandonos",
				label: "Abandonos",
				type: "number",
				required: false,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
];

export const graduateFormTemplates: FormTemplateDef[] = [
	{
		id: "7",
		title: "Graduados",
		description: "Numero de graduados por modalidad y sexo",
		module: FormModules.graduate,
		isActive: true,
		hasBulk: true,
		step: 7,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: graduationModalities.map((modality) => ({
					value: modality.id,
					label: modality.name,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "8",
		title: "Graduados nivel académico",
		description: "Numero de graduados por nivel académico y sexo",
		module: FormModules.graduate,
		isActive: true,
		hasBulk: true,
		step: 8,
		fields: [
			{
				id: "1",
				name: "academic_level",
				label: "Nivel Académico",
				type: "select",
				required: true,
				options: academicLevels.map((level) => ({
					value: level.id,
					label: level.name,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
];

export const teacherFormTemplates: FormTemplateDef[] = [
	{
		id: "9",
		title: "Docentes",
		description: "Numero de docentes por nivel académico",
		module: FormModules.teacher,
		isActive: true,
		hasBulk: true,
		step: 9,
		fields: [
			{
				id: "1",
				name: "paterno",
				label: "Apellido Paterno",
				type: "text",
				required: false,
			},
			{
				id: "2",
				name: "materno",
				label: "Apellido Materno",
				type: "text",
				required: true,
			},
			{
				id: "3",
				name: "nombres",
				label: "Nombres",
				type: "text",
				required: true,
			},
			{
				id: "4",
				name: "ci",
				label: "Nro. Carnet",
				type: "text",
				required: true,
			},
			{
				id: "5",
				name: "cel",
				label: "Nro. Celular",
				type: "number",
				required: true,
			},
			{
				id: "6",
				name: "carga_horaria",
				label: "Carga Horaria",
				type: "select",
				required: false,
				options: workloads.map((workload) => ({
					value: workload.id,
					label: workload.name,
				})),
			},
			{
				id: "7",
				name: "categoria",
				label: "Categoría",
				type: "select",
				required: false,
				options: teachingCategories.map((category) => ({
					value: category.id,
					label: category.name,
				})),
			},
			{
				id: "8",
				name: "nivel_academico",
				label: "Nivel académico alcanzado",
				type: "select",
				required: true,
				options: teachingAcademicLevels.map((level) => ({
					value: level.id,
					label: level.name,
				})),
			},
			{
				id: "9",
				name: "profesion",
				label: "Profesión",
				type: "text",
				required: true,
			},
		],
	},
];

export const scholarshipFormTemplates: FormTemplateDef[] = [
	{
		id: "10",
		title: "Beca Alimentacion",
		description: "Numero de beca alimentacion por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: true,
		step: 10,
		fields: [
			{
				id: "1",
				name: "tipo",
				label: "Tipo",
				type: "select",
				required: true,
				options: [
					{ value: "parcial", label: "Parcial" },
					{ value: "completa", label: "Completa" },
				],
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "11",
		title: "Auxiliares de docencia",
		description: "Numero de auxiliares de docencia por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: true,
		step: 11,
		fields: [
			{
				id: "1",
				name: "tipo",
				label: "Tipo",
				type: "select",
				required: true,
				options: [
					{ value: "titulares", label: "Titulares" },
					{ value: "invitados", label: "Invitados" },
				],
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "12",
		title: "Beca Investigación",
		description: "Numero de beca investigacion por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 12,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "13",
		title: "Beca Graduacion",
		description: "Numero de beca graduacion por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 13,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "14",
		title: "Beca Trabajo",
		description: "Numero de beca trabajo por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 14,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
];
