import { FormModules, type FormTemplateDef } from "#/shared/types/dynamic-form";
import {
	academicLevels,
	graduationModalities,
	modalities,
	teachingAcademicLevels,
	teachingCategories,
	workloads,
} from "./seed-data";

export const studentFormTemplates: FormTemplateDef[] = [
	{
		id: "1",
		periodId: "2026",
		title: "Postulantes",
		shortTitle: "Postulantes",
		description: "Llenado de datos de postulantes por sexo para cada modalidad",
		module: FormModules.student,
		isActive: true,
		step: 1,
		hasBulk: true,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: modalities.map((modality) => ({
					value: modality.id,
					label: modality.modality,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "2",
		periodId: "2026",
		title: "Postulantes Admitidos",
		shortTitle: "Post. Admitidos",
		description:
			"Llenado de datos de postulantes admitidos por sexo para cada modalidad",
		module: FormModules.student,
		isActive: true,
		hasBulk: true,
		step: 2,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: modalities.map((modality) => ({
					value: modality.id,
					label: modality.modality,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "3",
		periodId: "2026",
		title: "Matrícula",
		shortTitle: "Matrícula",
		description: "Llenado de datos de estudiantes por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 3,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "4",
		periodId: "2026",
		title: "Matricula Nuevos",
		shortTitle: "Matric. Nuevos",
		description: "Llenado de datos de estudiantes nuevos por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 4,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "5",
		periodId: "2026",
		title: "Estudiantes Programados",
		shortTitle: "Estud. Programados",
		description: "Llenado de datos de estudiantes programados por sexo",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 5,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "6",
		periodId: "2026",
		title: "Evaluacion Quantitativa",
		shortTitle: "Eval. Quantitativa",
		description: "Número de materias aprobadas, reprobadas y abandonos",
		module: FormModules.student,
		isActive: true,
		hasBulk: false,
		step: 6,
		fields: [
			{
				id: "1",
				name: "aprobados",
				label: "Aprobados",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "reprobados",
				label: "Reprobados",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "abandonos",
				label: "Abandonos",
				type: "number",
				required: false,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
];

export const graduateFormTemplates: FormTemplateDef[] = [
	{
		id: "7",
		periodId: "2026",
		title: "Graduados",
		shortTitle: "Graduados",
		description: "Llenado de datos de graduados por sexo para cada modalidad",
		module: FormModules.graduate,
		isActive: true,
		hasBulk: true,
		step: 7,
		fields: [
			{
				id: "1",
				name: "modalidad",
				label: "Modalidad",
				type: "select",
				required: true,
				options: graduationModalities.map((modality) => ({
					value: modality.id,
					label: modality.name,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "8",
		periodId: "2026",
		title: "Graduados por nivel académico",
		shortTitle: "Grad. nivel académico",
		description:
			"Llenado de datos de graduados por sexo para cada nivel académico",
		module: FormModules.graduate,
		isActive: true,
		hasBulk: true,
		step: 8,
		fields: [
			{
				id: "1",
				name: "academic_level",
				label: "Nivel Académico",
				type: "select",
				required: true,
				options: academicLevels.map((level) => ({
					value: level.id,
					label: level.name,
				})),
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
];

export const teacherFormTemplates: FormTemplateDef[] = [
	{
		id: "9",
		periodId: "2026",
		title: "Docentes",
		shortTitle: "Docentes",
		description: "Nomina de docentes, segun formulario para cada docente",
		module: FormModules.teacher,
		isActive: true,
		hasBulk: true,
		step: 9,
		fields: [
			{
				id: "1",
				name: "paterno",
				label: "Apellido Paterno",
				type: "text",
				required: false,
			},
			{
				id: "2",
				name: "materno",
				label: "Apellido Materno",
				type: "text",
				required: true,
			},
			{
				id: "3",
				name: "nombres",
				label: "Nombres",
				type: "text",
				required: true,
			},
			{
				id: "4",
				name: "ci",
				label: "Nro. Carnet",
				type: "text",
				required: true,
			},
			{
				id: "5",
				name: "cel",
				label: "Nro. Celular",
				type: "number",
				required: true,
			},
			{
				id: "6",
				name: "carga_horaria",
				label: "Carga Horaria",
				type: "select",
				required: false,
				options: workloads.map((workload) => ({
					value: workload.id,
					label: workload.name,
				})),
			},
			{
				id: "7",
				name: "categoria",
				label: "Categoría",
				type: "select",
				required: false,
				options: teachingCategories.map((category) => ({
					value: category.id,
					label: category.name,
				})),
			},
			{
				id: "8",
				name: "nivel_academico",
				label: "Nivel académico alcanzado",
				type: "select",
				required: true,
				options: teachingAcademicLevels.map((level) => ({
					value: level.id,
					label: level.name,
				})),
			},
			{
				id: "9",
				name: "profesion",
				label: "Profesión",
				type: "text",
				required: true,
			},
		],
	},
];

export const scholarshipFormTemplates: FormTemplateDef[] = [
	{
		id: "10",
		periodId: "2026",
		title: "Beca Alimentacion",
		shortTitle: "Alimentacion",
		description: "Llenado de datos de beca alimentacion por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: true,
		step: 10,
		fields: [
			{
				id: "1",
				name: "tipo",
				label: "Tipo",
				type: "select",
				required: true,
				options: [
					{ value: "parcial", label: "Parcial" },
					{ value: "completa", label: "Completa" },
				],
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "11",
		periodId: "2026",
		title: "Auxiliares de docencia",
		shortTitle: "Aux. Docencia",
		description: "Llenado de datos de auxiliares de docencia por tipo y sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: true,
		step: 11,
		fields: [
			{
				id: "1",
				name: "tipo",
				label: "Tipo",
				type: "select",
				required: true,
				options: [
					{ value: "titulares", label: "Titulares" },
					{ value: "invitados", label: "Invitados" },
				],
			},
			{
				id: "2",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "4",
				name: "total",
				label: "Total",
				type: "number",
				required: true,
			},
		],
	},
	{
		id: "12",
		periodId: "2026",
		title: "Beca Investigación",
		shortTitle: "Investigación",
		description: "Llenado de datos de beca investigacion por sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 12,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "13",
		periodId: "2026",
		title: "Beca Graduacion",
		shortTitle: "Graduacion",
		description: "Llenado de datos de beca graduacion por sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 13,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
	{
		id: "14",
		periodId: "2026",
		title: "Beca Trabajo",
		shortTitle: "Trabajo",
		description: "Llenado de datos de beca trabajo por sexo",
		module: FormModules.scholarships,
		isActive: true,
		hasBulk: false,
		step: 14,
		fields: [
			{
				id: "1",
				name: "masculino",
				label: "Masculino",
				type: "number",
				required: true,
			},
			{
				id: "2",
				name: "femenino",
				label: "Femenino",
				type: "number",
				required: true,
			},
			{
				id: "3",
				name: "total",
				label: "Total",
				type: "number",
				required: false,
			},
		],
	},
];
