version: '3.8'

services:
  uatf-forms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uatf-forms
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
