/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalksIndexRouteImport } from './routes/talks.index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as TeacherReportTeachNumModRouteImport } from './routes/teacher-report/teach-num-mod'
import { Route as TeacherReportTeachNumAcadRouteImport } from './routes/teacher-report/teach-num-acad'
import { Route as TeacherReportTeachListRouteImport } from './routes/teacher-report/teach-list'
import { Route as TalksSlugRouteImport } from './routes/talks.$slug'
import { Route as StudentReportStuNumProgSexRouteImport } from './routes/student-report/stu-num-prog-sex'
import { Route as StudentReportStuNumPassFailDropRouteImport } from './routes/student-report/stu-num-pass-fail-drop'
import { Route as StudentReportStuNumAppCatSexRouteImport } from './routes/student-report/stu-num-app-cat-sex'
import { Route as StudentReportStuNumAppAdmCatSexRouteImport } from './routes/student-report/stu-num-app-adm-cat-sex'
import { Route as StudentReportStuEnrSexRouteImport } from './routes/student-report/stu-enr-sex'
import { Route as StudentReportStuEnrRegSexRouteImport } from './routes/student-report/stu-enr-reg-sex'
import { Route as StudentReportStuEnrNewSexRouteImport } from './routes/student-report/stu-enr-new-sex'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as ScholarshipReportSchWorkRouteImport } from './routes/scholarship-report/sch-work'
import { Route as ScholarshipReportSchResearchRouteImport } from './routes/scholarship-report/sch-research'
import { Route as ScholarshipReportSchLabRouteImport } from './routes/scholarship-report/sch-lab'
import { Route as ScholarshipReportSchGraduationRouteImport } from './routes/scholarship-report/sch-graduation'
import { Route as ScholarshipReportSchFoodTypeSexRouteImport } from './routes/scholarship-report/sch-food-type-sex'
import { Route as ScholarshipReportSchBoardingRouteImport } from './routes/scholarship-report/sch-boarding'
import { Route as ScholarshipReportSchAssistantsRouteImport } from './routes/scholarship-report/sch-assistants'
import { Route as GraduatesReportGradNumModSexRouteImport } from './routes/graduates-report/grad-num-mod-sex'
import { Route as GraduatesReportGradNumAcadSexRouteImport } from './routes/graduates-report/grad-num-acad-sex'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportTeachNumModRoute =
  TeacherReportTeachNumModRouteImport.update({
    id: '/teacher-report/teach-num-mod',
    path: '/teacher-report/teach-num-mod',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherReportTeachNumAcadRoute =
  TeacherReportTeachNumAcadRouteImport.update({
    id: '/teacher-report/teach-num-acad',
    path: '/teacher-report/teach-num-acad',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherReportTeachListRoute = TeacherReportTeachListRouteImport.update({
  id: '/teacher-report/teach-list',
  path: '/teacher-report/teach-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReportStuNumProgSexRoute =
  StudentReportStuNumProgSexRouteImport.update({
    id: '/student-report/stu-num-prog-sex',
    path: '/student-report/stu-num-prog-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReportStuNumPassFailDropRoute =
  StudentReportStuNumPassFailDropRouteImport.update({
    id: '/student-report/stu-num-pass-fail-drop',
    path: '/student-report/stu-num-pass-fail-drop',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReportStuNumAppCatSexRoute =
  StudentReportStuNumAppCatSexRouteImport.update({
    id: '/student-report/stu-num-app-cat-sex',
    path: '/student-report/stu-num-app-cat-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReportStuNumAppAdmCatSexRoute =
  StudentReportStuNumAppAdmCatSexRouteImport.update({
    id: '/student-report/stu-num-app-adm-cat-sex',
    path: '/student-report/stu-num-app-adm-cat-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReportStuEnrSexRoute = StudentReportStuEnrSexRouteImport.update({
  id: '/student-report/stu-enr-sex',
  path: '/student-report/stu-enr-sex',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReportStuEnrRegSexRoute =
  StudentReportStuEnrRegSexRouteImport.update({
    id: '/student-report/stu-enr-reg-sex',
    path: '/student-report/stu-enr-reg-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentReportStuEnrNewSexRoute =
  StudentReportStuEnrNewSexRouteImport.update({
    id: '/student-report/stu-enr-new-sex',
    path: '/student-report/stu-enr-new-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipReportSchWorkRoute =
  ScholarshipReportSchWorkRouteImport.update({
    id: '/scholarship-report/sch-work',
    path: '/scholarship-report/sch-work',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipReportSchResearchRoute =
  ScholarshipReportSchResearchRouteImport.update({
    id: '/scholarship-report/sch-research',
    path: '/scholarship-report/sch-research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipReportSchLabRoute = ScholarshipReportSchLabRouteImport.update({
  id: '/scholarship-report/sch-lab',
  path: '/scholarship-report/sch-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipReportSchGraduationRoute =
  ScholarshipReportSchGraduationRouteImport.update({
    id: '/scholarship-report/sch-graduation',
    path: '/scholarship-report/sch-graduation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipReportSchFoodTypeSexRoute =
  ScholarshipReportSchFoodTypeSexRouteImport.update({
    id: '/scholarship-report/sch-food-type-sex',
    path: '/scholarship-report/sch-food-type-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipReportSchBoardingRoute =
  ScholarshipReportSchBoardingRouteImport.update({
    id: '/scholarship-report/sch-boarding',
    path: '/scholarship-report/sch-boarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScholarshipReportSchAssistantsRoute =
  ScholarshipReportSchAssistantsRouteImport.update({
    id: '/scholarship-report/sch-assistants',
    path: '/scholarship-report/sch-assistants',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraduatesReportGradNumModSexRoute =
  GraduatesReportGradNumModSexRouteImport.update({
    id: '/graduates-report/grad-num-mod-sex',
    path: '/graduates-report/grad-num-mod-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const GraduatesReportGradNumAcadSexRoute =
  GraduatesReportGradNumAcadSexRouteImport.update({
    id: '/graduates-report/grad-num-acad-sex',
    path: '/graduates-report/grad-num-acad-sex',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/graduates-report/grad-num-acad-sex': typeof GraduatesReportGradNumAcadSexRoute
  '/graduates-report/grad-num-mod-sex': typeof GraduatesReportGradNumModSexRoute
  '/scholarship-report/sch-assistants': typeof ScholarshipReportSchAssistantsRoute
  '/scholarship-report/sch-boarding': typeof ScholarshipReportSchBoardingRoute
  '/scholarship-report/sch-food-type-sex': typeof ScholarshipReportSchFoodTypeSexRoute
  '/scholarship-report/sch-graduation': typeof ScholarshipReportSchGraduationRoute
  '/scholarship-report/sch-lab': typeof ScholarshipReportSchLabRoute
  '/scholarship-report/sch-research': typeof ScholarshipReportSchResearchRoute
  '/scholarship-report/sch-work': typeof ScholarshipReportSchWorkRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/student-report/stu-enr-new-sex': typeof StudentReportStuEnrNewSexRoute
  '/student-report/stu-enr-reg-sex': typeof StudentReportStuEnrRegSexRoute
  '/student-report/stu-enr-sex': typeof StudentReportStuEnrSexRoute
  '/student-report/stu-num-app-adm-cat-sex': typeof StudentReportStuNumAppAdmCatSexRoute
  '/student-report/stu-num-app-cat-sex': typeof StudentReportStuNumAppCatSexRoute
  '/student-report/stu-num-pass-fail-drop': typeof StudentReportStuNumPassFailDropRoute
  '/student-report/stu-num-prog-sex': typeof StudentReportStuNumProgSexRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/teacher-report/teach-list': typeof TeacherReportTeachListRoute
  '/teacher-report/teach-num-acad': typeof TeacherReportTeachNumAcadRoute
  '/teacher-report/teach-num-mod': typeof TeacherReportTeachNumModRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/graduates-report/grad-num-acad-sex': typeof GraduatesReportGradNumAcadSexRoute
  '/graduates-report/grad-num-mod-sex': typeof GraduatesReportGradNumModSexRoute
  '/scholarship-report/sch-assistants': typeof ScholarshipReportSchAssistantsRoute
  '/scholarship-report/sch-boarding': typeof ScholarshipReportSchBoardingRoute
  '/scholarship-report/sch-food-type-sex': typeof ScholarshipReportSchFoodTypeSexRoute
  '/scholarship-report/sch-graduation': typeof ScholarshipReportSchGraduationRoute
  '/scholarship-report/sch-lab': typeof ScholarshipReportSchLabRoute
  '/scholarship-report/sch-research': typeof ScholarshipReportSchResearchRoute
  '/scholarship-report/sch-work': typeof ScholarshipReportSchWorkRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/student-report/stu-enr-new-sex': typeof StudentReportStuEnrNewSexRoute
  '/student-report/stu-enr-reg-sex': typeof StudentReportStuEnrRegSexRoute
  '/student-report/stu-enr-sex': typeof StudentReportStuEnrSexRoute
  '/student-report/stu-num-app-adm-cat-sex': typeof StudentReportStuNumAppAdmCatSexRoute
  '/student-report/stu-num-app-cat-sex': typeof StudentReportStuNumAppCatSexRoute
  '/student-report/stu-num-pass-fail-drop': typeof StudentReportStuNumPassFailDropRoute
  '/student-report/stu-num-prog-sex': typeof StudentReportStuNumProgSexRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/teacher-report/teach-list': typeof TeacherReportTeachListRoute
  '/teacher-report/teach-num-acad': typeof TeacherReportTeachNumAcadRoute
  '/teacher-report/teach-num-mod': typeof TeacherReportTeachNumModRoute
  '/schedule': typeof ScheduleIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/talks': typeof TalksIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/graduates-report/grad-num-acad-sex': typeof GraduatesReportGradNumAcadSexRoute
  '/graduates-report/grad-num-mod-sex': typeof GraduatesReportGradNumModSexRoute
  '/scholarship-report/sch-assistants': typeof ScholarshipReportSchAssistantsRoute
  '/scholarship-report/sch-boarding': typeof ScholarshipReportSchBoardingRoute
  '/scholarship-report/sch-food-type-sex': typeof ScholarshipReportSchFoodTypeSexRoute
  '/scholarship-report/sch-graduation': typeof ScholarshipReportSchGraduationRoute
  '/scholarship-report/sch-lab': typeof ScholarshipReportSchLabRoute
  '/scholarship-report/sch-research': typeof ScholarshipReportSchResearchRoute
  '/scholarship-report/sch-work': typeof ScholarshipReportSchWorkRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/student-report/stu-enr-new-sex': typeof StudentReportStuEnrNewSexRoute
  '/student-report/stu-enr-reg-sex': typeof StudentReportStuEnrRegSexRoute
  '/student-report/stu-enr-sex': typeof StudentReportStuEnrSexRoute
  '/student-report/stu-num-app-adm-cat-sex': typeof StudentReportStuNumAppAdmCatSexRoute
  '/student-report/stu-num-app-cat-sex': typeof StudentReportStuNumAppCatSexRoute
  '/student-report/stu-num-pass-fail-drop': typeof StudentReportStuNumPassFailDropRoute
  '/student-report/stu-num-prog-sex': typeof StudentReportStuNumProgSexRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/teacher-report/teach-list': typeof TeacherReportTeachListRoute
  '/teacher-report/teach-num-acad': typeof TeacherReportTeachNumAcadRoute
  '/teacher-report/teach-num-mod': typeof TeacherReportTeachNumModRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/graduates-report/grad-num-acad-sex'
    | '/graduates-report/grad-num-mod-sex'
    | '/scholarship-report/sch-assistants'
    | '/scholarship-report/sch-boarding'
    | '/scholarship-report/sch-food-type-sex'
    | '/scholarship-report/sch-graduation'
    | '/scholarship-report/sch-lab'
    | '/scholarship-report/sch-research'
    | '/scholarship-report/sch-work'
    | '/speakers/$slug'
    | '/student-report/stu-enr-new-sex'
    | '/student-report/stu-enr-reg-sex'
    | '/student-report/stu-enr-sex'
    | '/student-report/stu-num-app-adm-cat-sex'
    | '/student-report/stu-num-app-cat-sex'
    | '/student-report/stu-num-pass-fail-drop'
    | '/student-report/stu-num-prog-sex'
    | '/talks/$slug'
    | '/teacher-report/teach-list'
    | '/teacher-report/teach-num-acad'
    | '/teacher-report/teach-num-mod'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/graduates-report/grad-num-acad-sex'
    | '/graduates-report/grad-num-mod-sex'
    | '/scholarship-report/sch-assistants'
    | '/scholarship-report/sch-boarding'
    | '/scholarship-report/sch-food-type-sex'
    | '/scholarship-report/sch-graduation'
    | '/scholarship-report/sch-lab'
    | '/scholarship-report/sch-research'
    | '/scholarship-report/sch-work'
    | '/speakers/$slug'
    | '/student-report/stu-enr-new-sex'
    | '/student-report/stu-enr-reg-sex'
    | '/student-report/stu-enr-sex'
    | '/student-report/stu-num-app-adm-cat-sex'
    | '/student-report/stu-num-app-cat-sex'
    | '/student-report/stu-num-pass-fail-drop'
    | '/student-report/stu-num-prog-sex'
    | '/talks/$slug'
    | '/teacher-report/teach-list'
    | '/teacher-report/teach-num-acad'
    | '/teacher-report/teach-num-mod'
    | '/schedule'
    | '/speakers'
    | '/talks'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/graduates-report/grad-num-acad-sex'
    | '/graduates-report/grad-num-mod-sex'
    | '/scholarship-report/sch-assistants'
    | '/scholarship-report/sch-boarding'
    | '/scholarship-report/sch-food-type-sex'
    | '/scholarship-report/sch-graduation'
    | '/scholarship-report/sch-lab'
    | '/scholarship-report/sch-research'
    | '/scholarship-report/sch-work'
    | '/speakers/$slug'
    | '/student-report/stu-enr-new-sex'
    | '/student-report/stu-enr-reg-sex'
    | '/student-report/stu-enr-sex'
    | '/student-report/stu-num-app-adm-cat-sex'
    | '/student-report/stu-num-app-cat-sex'
    | '/student-report/stu-num-pass-fail-drop'
    | '/student-report/stu-num-prog-sex'
    | '/talks/$slug'
    | '/teacher-report/teach-list'
    | '/teacher-report/teach-num-acad'
    | '/teacher-report/teach-num-mod'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  GraduatesReportGradNumAcadSexRoute: typeof GraduatesReportGradNumAcadSexRoute
  GraduatesReportGradNumModSexRoute: typeof GraduatesReportGradNumModSexRoute
  ScholarshipReportSchAssistantsRoute: typeof ScholarshipReportSchAssistantsRoute
  ScholarshipReportSchBoardingRoute: typeof ScholarshipReportSchBoardingRoute
  ScholarshipReportSchFoodTypeSexRoute: typeof ScholarshipReportSchFoodTypeSexRoute
  ScholarshipReportSchGraduationRoute: typeof ScholarshipReportSchGraduationRoute
  ScholarshipReportSchLabRoute: typeof ScholarshipReportSchLabRoute
  ScholarshipReportSchResearchRoute: typeof ScholarshipReportSchResearchRoute
  ScholarshipReportSchWorkRoute: typeof ScholarshipReportSchWorkRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  StudentReportStuEnrNewSexRoute: typeof StudentReportStuEnrNewSexRoute
  StudentReportStuEnrRegSexRoute: typeof StudentReportStuEnrRegSexRoute
  StudentReportStuEnrSexRoute: typeof StudentReportStuEnrSexRoute
  StudentReportStuNumAppAdmCatSexRoute: typeof StudentReportStuNumAppAdmCatSexRoute
  StudentReportStuNumAppCatSexRoute: typeof StudentReportStuNumAppCatSexRoute
  StudentReportStuNumPassFailDropRoute: typeof StudentReportStuNumPassFailDropRoute
  StudentReportStuNumProgSexRoute: typeof StudentReportStuNumProgSexRoute
  TalksSlugRoute: typeof TalksSlugRoute
  TeacherReportTeachListRoute: typeof TeacherReportTeachListRoute
  TeacherReportTeachNumAcadRoute: typeof TeacherReportTeachNumAcadRoute
  TeacherReportTeachNumModRoute: typeof TeacherReportTeachNumModRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-report/teach-num-mod': {
      id: '/teacher-report/teach-num-mod'
      path: '/teacher-report/teach-num-mod'
      fullPath: '/teacher-report/teach-num-mod'
      preLoaderRoute: typeof TeacherReportTeachNumModRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-report/teach-num-acad': {
      id: '/teacher-report/teach-num-acad'
      path: '/teacher-report/teach-num-acad'
      fullPath: '/teacher-report/teach-num-acad'
      preLoaderRoute: typeof TeacherReportTeachNumAcadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-report/teach-list': {
      id: '/teacher-report/teach-list'
      path: '/teacher-report/teach-list'
      fullPath: '/teacher-report/teach-list'
      preLoaderRoute: typeof TeacherReportTeachListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-num-prog-sex': {
      id: '/student-report/stu-num-prog-sex'
      path: '/student-report/stu-num-prog-sex'
      fullPath: '/student-report/stu-num-prog-sex'
      preLoaderRoute: typeof StudentReportStuNumProgSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-num-pass-fail-drop': {
      id: '/student-report/stu-num-pass-fail-drop'
      path: '/student-report/stu-num-pass-fail-drop'
      fullPath: '/student-report/stu-num-pass-fail-drop'
      preLoaderRoute: typeof StudentReportStuNumPassFailDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-num-app-cat-sex': {
      id: '/student-report/stu-num-app-cat-sex'
      path: '/student-report/stu-num-app-cat-sex'
      fullPath: '/student-report/stu-num-app-cat-sex'
      preLoaderRoute: typeof StudentReportStuNumAppCatSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-num-app-adm-cat-sex': {
      id: '/student-report/stu-num-app-adm-cat-sex'
      path: '/student-report/stu-num-app-adm-cat-sex'
      fullPath: '/student-report/stu-num-app-adm-cat-sex'
      preLoaderRoute: typeof StudentReportStuNumAppAdmCatSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-enr-sex': {
      id: '/student-report/stu-enr-sex'
      path: '/student-report/stu-enr-sex'
      fullPath: '/student-report/stu-enr-sex'
      preLoaderRoute: typeof StudentReportStuEnrSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-enr-reg-sex': {
      id: '/student-report/stu-enr-reg-sex'
      path: '/student-report/stu-enr-reg-sex'
      fullPath: '/student-report/stu-enr-reg-sex'
      preLoaderRoute: typeof StudentReportStuEnrRegSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/stu-enr-new-sex': {
      id: '/student-report/stu-enr-new-sex'
      path: '/student-report/stu-enr-new-sex'
      fullPath: '/student-report/stu-enr-new-sex'
      preLoaderRoute: typeof StudentReportStuEnrNewSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-work': {
      id: '/scholarship-report/sch-work'
      path: '/scholarship-report/sch-work'
      fullPath: '/scholarship-report/sch-work'
      preLoaderRoute: typeof ScholarshipReportSchWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-research': {
      id: '/scholarship-report/sch-research'
      path: '/scholarship-report/sch-research'
      fullPath: '/scholarship-report/sch-research'
      preLoaderRoute: typeof ScholarshipReportSchResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-lab': {
      id: '/scholarship-report/sch-lab'
      path: '/scholarship-report/sch-lab'
      fullPath: '/scholarship-report/sch-lab'
      preLoaderRoute: typeof ScholarshipReportSchLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-graduation': {
      id: '/scholarship-report/sch-graduation'
      path: '/scholarship-report/sch-graduation'
      fullPath: '/scholarship-report/sch-graduation'
      preLoaderRoute: typeof ScholarshipReportSchGraduationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-food-type-sex': {
      id: '/scholarship-report/sch-food-type-sex'
      path: '/scholarship-report/sch-food-type-sex'
      fullPath: '/scholarship-report/sch-food-type-sex'
      preLoaderRoute: typeof ScholarshipReportSchFoodTypeSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-boarding': {
      id: '/scholarship-report/sch-boarding'
      path: '/scholarship-report/sch-boarding'
      fullPath: '/scholarship-report/sch-boarding'
      preLoaderRoute: typeof ScholarshipReportSchBoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/sch-assistants': {
      id: '/scholarship-report/sch-assistants'
      path: '/scholarship-report/sch-assistants'
      fullPath: '/scholarship-report/sch-assistants'
      preLoaderRoute: typeof ScholarshipReportSchAssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates-report/grad-num-mod-sex': {
      id: '/graduates-report/grad-num-mod-sex'
      path: '/graduates-report/grad-num-mod-sex'
      fullPath: '/graduates-report/grad-num-mod-sex'
      preLoaderRoute: typeof GraduatesReportGradNumModSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates-report/grad-num-acad-sex': {
      id: '/graduates-report/grad-num-acad-sex'
      path: '/graduates-report/grad-num-acad-sex'
      fullPath: '/graduates-report/grad-num-acad-sex'
      preLoaderRoute: typeof GraduatesReportGradNumAcadSexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  GraduatesReportGradNumAcadSexRoute: GraduatesReportGradNumAcadSexRoute,
  GraduatesReportGradNumModSexRoute: GraduatesReportGradNumModSexRoute,
  ScholarshipReportSchAssistantsRoute: ScholarshipReportSchAssistantsRoute,
  ScholarshipReportSchBoardingRoute: ScholarshipReportSchBoardingRoute,
  ScholarshipReportSchFoodTypeSexRoute: ScholarshipReportSchFoodTypeSexRoute,
  ScholarshipReportSchGraduationRoute: ScholarshipReportSchGraduationRoute,
  ScholarshipReportSchLabRoute: ScholarshipReportSchLabRoute,
  ScholarshipReportSchResearchRoute: ScholarshipReportSchResearchRoute,
  ScholarshipReportSchWorkRoute: ScholarshipReportSchWorkRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  StudentReportStuEnrNewSexRoute: StudentReportStuEnrNewSexRoute,
  StudentReportStuEnrRegSexRoute: StudentReportStuEnrRegSexRoute,
  StudentReportStuEnrSexRoute: StudentReportStuEnrSexRoute,
  StudentReportStuNumAppAdmCatSexRoute: StudentReportStuNumAppAdmCatSexRoute,
  StudentReportStuNumAppCatSexRoute: StudentReportStuNumAppCatSexRoute,
  StudentReportStuNumPassFailDropRoute: StudentReportStuNumPassFailDropRoute,
  StudentReportStuNumProgSexRoute: StudentReportStuNumProgSexRoute,
  TalksSlugRoute: TalksSlugRoute,
  TeacherReportTeachListRoute: TeacherReportTeachListRoute,
  TeacherReportTeachNumAcadRoute: TeacherReportTeachNumAcadRoute,
  TeacherReportTeachNumModRoute: TeacherReportTeachNumModRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
