/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherReportFormIdRouteImport } from './routes/teacher-report/$formId'
import { Route as StudentReportFormIdRouteImport } from './routes/student-report/$formId'
import { Route as ScholarshipReportFormIdRouteImport } from './routes/scholarship-report/$formId'
import { Route as GraduatesReportFormIdRouteImport } from './routes/graduates-report/$formId'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoFormIdRouteImport } from './routes/demo/$formId'
import { Route as DashboardTableRouteImport } from './routes/dashboard/table'
import { Route as DashboardProgramsRouteImport } from './routes/dashboard/programs'
import { Route as DashboardModalitiesRouteImport } from './routes/dashboard/modalities'
import { Route as DashboardGraduationModalitiesRouteImport } from './routes/dashboard/graduation-modalities'
import { Route as DashboardFormBuilderRouteImport } from './routes/dashboard/form-builder'
import { Route as DashboardFacultiesRouteImport } from './routes/dashboard/faculties'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardReportsTemplateIdModuleRouteImport } from './routes/dashboard/reports/$templateId/$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportFormIdRoute = TeacherReportFormIdRouteImport.update({
  id: '/teacher-report/$formId',
  path: '/teacher-report/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentReportFormIdRoute = StudentReportFormIdRouteImport.update({
  id: '/student-report/$formId',
  path: '/student-report/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipReportFormIdRoute = ScholarshipReportFormIdRouteImport.update({
  id: '/scholarship-report/$formId',
  path: '/scholarship-report/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const GraduatesReportFormIdRoute = GraduatesReportFormIdRouteImport.update({
  id: '/graduates-report/$formId',
  path: '/graduates-report/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormIdRoute = DemoFormIdRouteImport.update({
  id: '/demo/$formId',
  path: '/demo/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTableRoute = DashboardTableRouteImport.update({
  id: '/dashboard/table',
  path: '/dashboard/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgramsRoute = DashboardProgramsRouteImport.update({
  id: '/dashboard/programs',
  path: '/dashboard/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModalitiesRoute = DashboardModalitiesRouteImport.update({
  id: '/dashboard/modalities',
  path: '/dashboard/modalities',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGraduationModalitiesRoute =
  DashboardGraduationModalitiesRouteImport.update({
    id: '/dashboard/graduation-modalities',
    path: '/dashboard/graduation-modalities',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardFormBuilderRoute = DashboardFormBuilderRouteImport.update({
  id: '/dashboard/form-builder',
  path: '/dashboard/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacultiesRoute = DashboardFacultiesRouteImport.update({
  id: '/dashboard/faculties',
  path: '/dashboard/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsTemplateIdModuleRoute =
  DashboardReportsTemplateIdModuleRouteImport.update({
    id: '/dashboard/reports/$templateId/$module',
    path: '/dashboard/reports/$templateId/$module',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/faculties': typeof DashboardFacultiesRoute
  '/dashboard/form-builder': typeof DashboardFormBuilderRoute
  '/dashboard/graduation-modalities': typeof DashboardGraduationModalitiesRoute
  '/dashboard/modalities': typeof DashboardModalitiesRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/table': typeof DashboardTableRoute
  '/demo/$formId': typeof DemoFormIdRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/graduates-report/$formId': typeof GraduatesReportFormIdRoute
  '/scholarship-report/$formId': typeof ScholarshipReportFormIdRoute
  '/student-report/$formId': typeof StudentReportFormIdRoute
  '/teacher-report/$formId': typeof TeacherReportFormIdRoute
  '/dashboard/reports/$templateId/$module': typeof DashboardReportsTemplateIdModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/faculties': typeof DashboardFacultiesRoute
  '/dashboard/form-builder': typeof DashboardFormBuilderRoute
  '/dashboard/graduation-modalities': typeof DashboardGraduationModalitiesRoute
  '/dashboard/modalities': typeof DashboardModalitiesRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/table': typeof DashboardTableRoute
  '/demo/$formId': typeof DemoFormIdRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/graduates-report/$formId': typeof GraduatesReportFormIdRoute
  '/scholarship-report/$formId': typeof ScholarshipReportFormIdRoute
  '/student-report/$formId': typeof StudentReportFormIdRoute
  '/teacher-report/$formId': typeof TeacherReportFormIdRoute
  '/dashboard/reports/$templateId/$module': typeof DashboardReportsTemplateIdModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/faculties': typeof DashboardFacultiesRoute
  '/dashboard/form-builder': typeof DashboardFormBuilderRoute
  '/dashboard/graduation-modalities': typeof DashboardGraduationModalitiesRoute
  '/dashboard/modalities': typeof DashboardModalitiesRoute
  '/dashboard/programs': typeof DashboardProgramsRoute
  '/dashboard/table': typeof DashboardTableRoute
  '/demo/$formId': typeof DemoFormIdRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/graduates-report/$formId': typeof GraduatesReportFormIdRoute
  '/scholarship-report/$formId': typeof ScholarshipReportFormIdRoute
  '/student-report/$formId': typeof StudentReportFormIdRoute
  '/teacher-report/$formId': typeof TeacherReportFormIdRoute
  '/dashboard/reports/$templateId/$module': typeof DashboardReportsTemplateIdModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/dashboard'
    | '/dashboard/faculties'
    | '/dashboard/form-builder'
    | '/dashboard/graduation-modalities'
    | '/dashboard/modalities'
    | '/dashboard/programs'
    | '/dashboard/table'
    | '/demo/$formId'
    | '/demo/storybook'
    | '/graduates-report/$formId'
    | '/scholarship-report/$formId'
    | '/student-report/$formId'
    | '/teacher-report/$formId'
    | '/dashboard/reports/$templateId/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/dashboard'
    | '/dashboard/faculties'
    | '/dashboard/form-builder'
    | '/dashboard/graduation-modalities'
    | '/dashboard/modalities'
    | '/dashboard/programs'
    | '/dashboard/table'
    | '/demo/$formId'
    | '/demo/storybook'
    | '/graduates-report/$formId'
    | '/scholarship-report/$formId'
    | '/student-report/$formId'
    | '/teacher-report/$formId'
    | '/dashboard/reports/$templateId/$module'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/dashboard'
    | '/dashboard/faculties'
    | '/dashboard/form-builder'
    | '/dashboard/graduation-modalities'
    | '/dashboard/modalities'
    | '/dashboard/programs'
    | '/dashboard/table'
    | '/demo/$formId'
    | '/demo/storybook'
    | '/graduates-report/$formId'
    | '/scholarship-report/$formId'
    | '/student-report/$formId'
    | '/teacher-report/$formId'
    | '/dashboard/reports/$templateId/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFacultiesRoute: typeof DashboardFacultiesRoute
  DashboardFormBuilderRoute: typeof DashboardFormBuilderRoute
  DashboardGraduationModalitiesRoute: typeof DashboardGraduationModalitiesRoute
  DashboardModalitiesRoute: typeof DashboardModalitiesRoute
  DashboardProgramsRoute: typeof DashboardProgramsRoute
  DashboardTableRoute: typeof DashboardTableRoute
  DemoFormIdRoute: typeof DemoFormIdRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  GraduatesReportFormIdRoute: typeof GraduatesReportFormIdRoute
  ScholarshipReportFormIdRoute: typeof ScholarshipReportFormIdRoute
  StudentReportFormIdRoute: typeof StudentReportFormIdRoute
  TeacherReportFormIdRoute: typeof TeacherReportFormIdRoute
  DashboardReportsTemplateIdModuleRoute: typeof DashboardReportsTemplateIdModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-report/$formId': {
      id: '/teacher-report/$formId'
      path: '/teacher-report/$formId'
      fullPath: '/teacher-report/$formId'
      preLoaderRoute: typeof TeacherReportFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-report/$formId': {
      id: '/student-report/$formId'
      path: '/student-report/$formId'
      fullPath: '/student-report/$formId'
      preLoaderRoute: typeof StudentReportFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship-report/$formId': {
      id: '/scholarship-report/$formId'
      path: '/scholarship-report/$formId'
      fullPath: '/scholarship-report/$formId'
      preLoaderRoute: typeof ScholarshipReportFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graduates-report/$formId': {
      id: '/graduates-report/$formId'
      path: '/graduates-report/$formId'
      fullPath: '/graduates-report/$formId'
      preLoaderRoute: typeof GraduatesReportFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$formId': {
      id: '/demo/$formId'
      path: '/demo/$formId'
      fullPath: '/demo/$formId'
      preLoaderRoute: typeof DemoFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/table': {
      id: '/dashboard/table'
      path: '/dashboard/table'
      fullPath: '/dashboard/table'
      preLoaderRoute: typeof DashboardTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/programs': {
      id: '/dashboard/programs'
      path: '/dashboard/programs'
      fullPath: '/dashboard/programs'
      preLoaderRoute: typeof DashboardProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/modalities': {
      id: '/dashboard/modalities'
      path: '/dashboard/modalities'
      fullPath: '/dashboard/modalities'
      preLoaderRoute: typeof DashboardModalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/graduation-modalities': {
      id: '/dashboard/graduation-modalities'
      path: '/dashboard/graduation-modalities'
      fullPath: '/dashboard/graduation-modalities'
      preLoaderRoute: typeof DashboardGraduationModalitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/form-builder': {
      id: '/dashboard/form-builder'
      path: '/dashboard/form-builder'
      fullPath: '/dashboard/form-builder'
      preLoaderRoute: typeof DashboardFormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/faculties': {
      id: '/dashboard/faculties'
      path: '/dashboard/faculties'
      fullPath: '/dashboard/faculties'
      preLoaderRoute: typeof DashboardFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports/$templateId/$module': {
      id: '/dashboard/reports/$templateId/$module'
      path: '/dashboard/reports/$templateId/$module'
      fullPath: '/dashboard/reports/$templateId/$module'
      preLoaderRoute: typeof DashboardReportsTemplateIdModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFacultiesRoute: DashboardFacultiesRoute,
  DashboardFormBuilderRoute: DashboardFormBuilderRoute,
  DashboardGraduationModalitiesRoute: DashboardGraduationModalitiesRoute,
  DashboardModalitiesRoute: DashboardModalitiesRoute,
  DashboardProgramsRoute: DashboardProgramsRoute,
  DashboardTableRoute: DashboardTableRoute,
  DemoFormIdRoute: DemoFormIdRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  GraduatesReportFormIdRoute: GraduatesReportFormIdRoute,
  ScholarshipReportFormIdRoute: ScholarshipReportFormIdRoute,
  StudentReportFormIdRoute: StudentReportFormIdRoute,
  TeacherReportFormIdRoute: TeacherReportFormIdRoute,
  DashboardReportsTemplateIdModuleRoute: DashboardReportsTemplateIdModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
